# SPDX-FileCopyrightText: 2026 Oggvik
# SPDX-License-Identifier: AGPL-3.0-or-later

modId=stop_minimizing_on_focus_loss
modName=Stop Minimizing on Focus Loss
modDescription=Prevents Minecraft fullscreen windows from minimizing when focus is lost.
modLicense=AGPL-3.0-or-later
modAuthor=Oggvik
modGroup=oggvik.mods.stopminimizingonfocusloss
modVersion=1.0.0
modCredits=
modContributors=
modDiscordInvite=
repoUrl=https://github.com/oggvik/stop-minimizing-on-focus-loss-mc
repoIssuesUrl=https://github.com/oggvik/stop-minimizing-on-focus-loss-mc/issues
repoSourcesUrl=https://github.com/oggvik/stop-minimizing-on-focus-loss-mc

deps.fabricLoader=0.19.3

org.gradle.jvmargs=-Xmx4G
org.gradle.parallel=true
