# SPDX-FileCopyrightText: 2026 Oggvik
# SPDX-License-Identifier: AGPL-3.0-or-later

modstitch.platform=fabric-loom-remap

mcVersion=1.20.1
parchment.version=2023.09.03

meta.mcDep=~1.20 <1.20.7

pub.stableMC=1.20,1.20.6

# Expose bundled translations without requiring the full Fabric API.
deps.fabricApiBase=0.4.32+1802ada577
deps.fabricResourceLoaderModule=fabric-resource-loader-v0
deps.fabricResourceLoader=0.11.12+fb82e9d777
