# SPDX-FileCopyrightText: 2026 Oggvik
# SPDX-License-Identifier: AGPL-3.0-or-later

modstitch.platform=fabric-loom-remap

mcVersion=1.16.5
parchment.version=2022.03.06

meta.mcDep=~1.16 <1.16.6

pub.stableMC=1.16,1.16.5

# Expose bundled translations without requiring the full Fabric API.
deps.fabricApiBase=0.4.0+3cc0f0907d
deps.fabricResourceLoaderModule=fabric-resource-loader-v0
deps.fabricResourceLoader=0.4.8+3cc0f0907d
