# SPDX-FileCopyrightText: 2026 Oggvik
# SPDX-License-Identifier: AGPL-3.0-or-later

modstitch.platform=fabric-loom-remap

mcVersion=1.17.1
parchment.version=2021.12.12

meta.mcDep=~1.17 <1.17.2

pub.stableMC=1.17,1.17.1

# Expose bundled translations without requiring the full Fabric API.
deps.fabricApiBase=0.4.0+cf39a74318
deps.fabricResourceLoaderModule=fabric-resource-loader-v0
deps.fabricResourceLoader=0.4.10+f09604ce18
