# SPDX-FileCopyrightText: 2026 Oggvik
# SPDX-License-Identifier: AGPL-3.0-or-later

modstitch.platform=fabric-loom-remap

mcVersion=1.15.2

meta.mcDep=~1.15 <1.15.3

pub.stableMC=1.15,1.15.2

# Expose bundled translations without requiring the full Fabric API.
deps.fabricApiBase=0.1.2+9826cad80c
deps.fabricResourceLoaderModule=fabric-resource-loader-v0
deps.fabricResourceLoader=0.1.11+c1455e800c
