# SPDX-FileCopyrightText: 2026 Oggvik
# SPDX-License-Identifier: AGPL-3.0-or-later

modstitch.platform=fabric-loom-remap

mcVersion=1.21.11

meta.mcDep=~1.21 <1.21.12

pub.stableMC=1.21,1.21.11

# Expose bundled translations without requiring the full Fabric API.
deps.fabricApiBase=1.0.5+4ebb5c083e
deps.fabricResourceLoaderModule=fabric-resource-loader-v1
deps.fabricResourceLoader=1.0.10+78c8b4663e
