# SPDX-FileCopyrightText: 2026 Oggvik
# SPDX-License-Identifier: AGPL-3.0-or-later

modLoader = "javafml"
loaderVersion = "[1,)"
issueTrackerURL = "https://github.com/oggvik/stop-minimizing-on-focus-loss-mc/issues"
license = "AGPL-3.0-or-later"

[[mods]]
modId = "stop_minimizing_on_focus_loss"
version = "1.0.0+1.20.1-neoforge"
displayName = "Stop Minimizing on Focus Loss"
displayURL = "https://github.com/oggvik/stop-minimizing-on-focus-loss-mc"
authors = "Oggvik"
displayTest = "IGNORE_SERVER_VERSION"
description = '''
Prevents Minecraft fullscreen windows from minimizing when focus is lost.
'''
logoFile = "icon.png"

[["dependencies.stop_minimizing_on_focus_loss"]]
modId = "forge"
mandatory = true
ordering = "NONE"
side = "CLIENT"

[["dependencies.stop_minimizing_on_focus_loss"]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1,1.20.2)"
ordering = "NONE"
side = "CLIENT"
